### ISSUE TITLE
ValueError:  File "Lepton.py", line 9, in <module>     from .ioctl_numbers import _IOR, _IOW

### ISSUE THREAD

**Issue by MakerStuff** [kekiefer/pylepton#24]
I've got the following error when running  Lepton.py:

`Traceback (most recent call last):
  File "Lepton.py", line 9, in <module>
    from .ioctl_numbers import _IOR, _IOW
ValueError: Attempted relative import in  non-package`

Pylepton_capture does not work as well. I tested it using ssh so im not sure wheater pylepton_overlay works or not.

**Comment by tmsd2001** [comment]
I think here is one point too much in the Lepton.py.
```
from .ioctl_numbers import _IOR, _IOW
```
```
from ioctl_numbers import _IOR, _IOW
```
